# Author: Satish Gaikwad <satish@satishweb.com>
FROM golang:alpine AS doh-build
LABEL MAINTAINER satish@satishweb.com

RUN apk add --no-cache git make jq curl

WORKDIR /src

ARG DOH_VERSION_LATEST

# Lets download latest version of DOH
RUN wget "https://github.com/m13253/dns-over-https/archive/${DOH_VERSION_LATEST}.zip" -O doh.zip \
    && unzip doh.zip \
    && rm doh.zip

# Lets compile DOH
RUN cd dns-over-https* \
    && make doh-server/doh-server \
    && mkdir /dist \
    && cp doh-server/doh-server /dist/doh-server \
    && echo ${DOH_VERSION_LATEST} > /dist/doh-server.version

FROM alpine:latest
LABEL MAINTAINER satish@satishweb.com

COPY --from=doh-build /dist /server
COPY doh-server.sample.conf /server/doh-server.sample.conf

# Install required packages by docker-entrypoint
RUN apk add --no-cache curl jq bash gettext

# Add docker entrypoint and make it executable
ADD docker-entrypoint /docker-entrypoint
RUN chmod u+x /docker-entrypoint

EXPOSE 8053

ENTRYPOINT ["/docker-entrypoint"]
CMD [ "/server/doh-server", "-conf", "/server/doh-server.conf" ]

# Healthcheck
# HEALTHCHECK --interval=1m --timeout=10s --start-period=10s wget localhost:8053/dns-query/ -O /dev/null || exit 1
