#!/bin/bash
# Author: Satish Gaikwad <satish@satishweb.com>
set -e

if [ -f /run/secrets/DEBUG ]; then
    export DEBUG=$(cat $i)
fi

if [ "$DEBUG" = "1" ]; then
    set -x
    BASH_CMD_FLAGS='-x'
fi

DOH_CONFIG_SAMPLE_FILE=/server/doh-server.sample.conf
DOH_CONFIG_FILE=/server/doh-server.conf

printf "|---------------------------------------------------------------------------------------------\n";
printf "| Starting DNS Over HTTP Service \n"

# Load env vars
printf "| ENTRYPOINT: \033[0;31mLoading docker secrets if found...\033[0m\n"
for i in $(env|grep '/run/secrets')
do
    varName=$(echo $i|awk -F '[=]' '{print $1}'|sed 's/_FILE//')
    varFile=$(echo $i|awk -F '[=]' '{print $2}')
    exportCmd="export $varName=$(cat $varFile)"
    echo "${exportCmd}" >> /etc/profile
    eval "${exportCmd}"
    printf "| ENTRYPOINT: Exporting var: $varName\n"
done

# Lets set default variable values
[[ "${UPSTREAM_DNS_SERVER}" == "" ]] && export UPSTREAM_DNS_SERVER="udp:unbound:53"
[[ "${DOH_HTTP_PREFIX}" == "" ]] && export DOH_HTTP_PREFIX="/getnsrecord"
[[ "${DOH_SERVER_LISTEN}" == "" ]] && export DOH_SERVER_LISTEN=":8053"
[[ "${DOH_SERVER_TIMEOUT}" == "" ]] && export DOH_SERVER_TIMEOUT="10"
[[ "${DOH_SERVER_TRIES}" == "" ]] && export DOH_SERVER_TRIES="3"
[[ "${DOH_SERVER_VERBOSE}" == "" ]] && export DOH_SERVER_VERBOSE="false"

# Lets copy default doh server config file if does not exists
if [[ ! -f ${DOH_CONFIG_FILE} ]]; then
  cp -rf ${DOH_CONFIG_SAMPLE_FILE} ${DOH_CONFIG_FILE}
fi

# lets generating config file by replacing all variables inside of it.
TMP_FILE=/tmp/doh-server.conf
cp ${DOH_CONFIG_FILE} ${TMP_FILE}
DOLLAR='$' envsubst < /tmp/doh-server.conf > ${DOH_CONFIG_FILE}
rm ${TMP_FILE}

# Check if app-config is present
if [ -f /app-config ]; then
    # We expect that app-config handles the launch of app command
    echo "| ENTRYPOINT: Executing app-config..."
    . /app-config "$@"
else
    # Let default CMD run if app-config is missing
    echo "| ENTRYPOINT: app-config was not available, running given parameters or default CMD..."
    exec $@
fi
